//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IRestServiceImpl")]
    public interface IRestServiceImpl {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestServiceImpl/XMLData", ReplyAction="http://tempuri.org/IRestServiceImpl/XMLDataResponse")]
        string XMLData(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestServiceImpl/XMLData", ReplyAction="http://tempuri.org/IRestServiceImpl/XMLDataResponse")]
        System.Threading.Tasks.Task<string> XMLDataAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestServiceImpl/JSONData", ReplyAction="http://tempuri.org/IRestServiceImpl/JSONDataResponse")]
        string JSONData(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestServiceImpl/JSONData", ReplyAction="http://tempuri.org/IRestServiceImpl/JSONDataResponse")]
        System.Threading.Tasks.Task<string> JSONDataAsync(string id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRestServiceImplChannel : WindowsFormsApplication1.ServiceReference1.IRestServiceImpl, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RestServiceImplClient : System.ServiceModel.ClientBase<WindowsFormsApplication1.ServiceReference1.IRestServiceImpl>, WindowsFormsApplication1.ServiceReference1.IRestServiceImpl {
        
        public RestServiceImplClient() {
        }
        
        public RestServiceImplClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RestServiceImplClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RestServiceImplClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RestServiceImplClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string XMLData(string id) {
            return base.Channel.XMLData(id);
        }
        
        public System.Threading.Tasks.Task<string> XMLDataAsync(string id) {
            return base.Channel.XMLDataAsync(id);
        }
        
        public string JSONData(string id) {
            return base.Channel.JSONData(id);
        }
        
        public System.Threading.Tasks.Task<string> JSONDataAsync(string id) {
            return base.Channel.JSONDataAsync(id);
        }
    }
}
